**Name:** Adithya Rao Kalathur

**Roll No.:** 251100610012

**Branch:** M.E. Computer Science and Engineering

**Course:** Applied Generative AI & ML

**Learner Id:** adithya.msismpl2025@learner.manipal.edu

# **Assignment problems (Lab Day 1) Date-12/08/2025**







1. WAP to search for a number 9 present in the list [89,14,21,34,55,3]
2. Find biggest and smallest from the list [89,14,21,34,55,3]
3. Filter the numbers greater than 50 from the list [89,14,21,34,55,3]
4. Count the number of elements in the list [89,14,21,34,55,3]
5. Find the sum and average of the numbers in the list [89,14,21,34,55,3]
6. WAP to perform bubble sort, quick sort and insertion sort using functions [89,14,21,34,55,3]
7. WAP to prompt the user for hours and rate per hour to compute gross pay.
   
   Enter Hours: 35
   
   Enter Rate: 2.75
   
   Pay: 96.25

8. Rewrite your pay compulation with time-and-a-half for overtime and create a function called computepay which takes two parameters(hours and rate).

   Enter Hours: 45

   Enter Rate: 10

   Pay: 475.0              
   
   475 = 40 * 10 + 5 * 15


 **1. WAP to search for a number 9 present in the list [89,14,21,34,55,3]**

In [ ]:
# List of numbers
numbers = [89, 14, 21, 34, 55, 3]

# Check if 9 is in the list
if 9 in numbers:
    print("9 is present in the list.")
else:
    print("9 is not present in the list.")


9 is not present in the list.


**2. Find biggest and smallest from the list [89,14,21,34,55,3]**

In [ ]:
numbers = [89, 14, 21, 34, 55, 3]

biggest = max(numbers)
smallest = min(numbers)

print(f"Biggest number: {biggest}")
print(f"Smallest number: {smallest}")


Biggest number: 89
Smallest number: 3


**3. Filter the numbers greater than 50 from the list [89,14,21,34,55,3]**

In [ ]:
numbers = [89, 14, 21, 34, 55, 3]

filtered_numbers = [num for num in numbers if num > 50]

print(f"Numbers greater than 50: {filtered_numbers}")


Numbers greater than 50: [89, 55]


**4. Count the number of elements in the list [89,14,21,34,55,3]**

In [ ]:
numbers = [89, 14, 21, 34, 55, 3]

count = len(numbers)

print(f"Number of elements in the list: {count}")


Number of elements in the list: 6


**5. Find the sum and average of the numbers in the list [89,14,21,34,55,3]**

In [ ]:
numbers = [89, 14, 21, 34, 55, 3]

sum_of_numbers = sum(numbers)
average = sum_of_numbers / len(numbers)

print(f"Sum of numbers: {sum_of_numbers}")
print(f"Average of numbers: {average}")


Sum of numbers: 216
Average of numbers: 36.0


**6. WAP to perform bubble sort, quick sort and insertion sort using functions**

In [ ]:
# Bubble Sort
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True
        if not swapped:
            break
    return arr

# Quick Sort
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

# Insertion Sort
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

# Test arrays
arr = [89,14,21,34,55,3]

# Testing all sorting algorithms
print("Bubble Sort Result:", bubble_sort(arr.copy()))
print("Quick Sort Result:", quick_sort(arr.copy()))
print("Insertion Sort Result:", insertion_sort(arr.copy()))


Bubble Sort Result: [3, 14, 21, 34, 55, 89]
Quick Sort Result: [3, 14, 21, 34, 55, 89]
Insertion Sort Result: [3, 14, 21, 34, 55, 89]


**7. WAP to prompt the user for hours and rate per hour to compute gross pay.**
   
   **Enter Hours: 35**
   
   **Enter Rate: 2.75**
   
   **Pay: 96.25**

In [ ]:
# WAP to compute gross pay

# Prompt the user for hours worked and rate per hour
hours = float(input("Enter Hours: "))
rate = float(input("Enter Rate: "))

# Calculate gross pay
pay = hours * rate

# Display the result
print(f"Pay: {pay}")


Enter Hours: 35
Enter Rate: 2.75
Pay: 96.25


**8. Rewrite your pay compulation with time-and-a-half for overtime and create a function called computepay which takes two parameters(hours and rate).**

   **Enter Hours: 45**

   **Enter Rate: 10**

   **Pay: 475.0**              
   
   **475 = 40 * 10 + 5 * 15**

In [ ]:
def computepay(hours, rate):
    # Check if hours worked are greater than 40
    if hours > 40:
        # Regular pay for the first 40 hours
        regular_pay = 40 * rate
        # Overtime pay for hours worked beyond 40 (time-and-a-half)
        overtime_pay = (hours - 40) * (rate * 1.5)
        # Total pay
        total_pay = regular_pay + overtime_pay
    else:
        # If no overtime, pay is just hours * rate
        total_pay = hours * rate

    return total_pay

# Prompt the user for input
hours = float(input("Enter Hours: "))
rate = float(input("Enter Rate: "))

# Calculate and print the total pay
pay = computepay(hours, rate)
print(f"Pay: {pay}")


Enter Hours: 45
Enter Rate: 10
Pay: 475.0


# **Lab Day-2 Date-19/08/2025**

In [ ]:
import scipy
print('Scipy:%s' % scipy.__version__)
import numpy
print("NumPy:", numpy.__version__)
import sklearn
print("scikit-learn:", sklearn.__version__)


Scipy:1.16.1
NumPy: 2.0.2
scikit-learn: 1.6.1


# using functions in python

In [ ]:
def add_numbers(x,y):
  return x+y

In [ ]:
a=15;b=1;
add_numbers(a,b)

16

In [ ]:
def add_numbers(x,y,z=None):
  if (z==None):
    return x+y
  else:
    return x+y+z

In [ ]:
print(add_numbers(30,3))

33


In [ ]:
print(add_numbers(10,20,30))

60


In [ ]:
def add_numbers(x,y,z=None,flag=False):
  if(flag):
    print('Flag is on!')
  if(z==None):
    return x+y
  else:
    return x+y+z

In [ ]:
print(add_numbers(10,20,25,flag=True))

Flag is on!
55


In [ ]:
#assign function to a variable
a=add_numbers
a(16,12)

28

In [ ]:
type('h')

str

In [ ]:
type(None)

NoneType

In [ ]:
type(0)

int

In [ ]:
type("hello")

str

In [ ]:
type(1.2123)

float

In [ ]:
type(add_numbers)

function

In [ ]:
x=(1,'a',2,'b',1.2)
type(x)

tuple

In [ ]:
# x.append(3.3)
# print(x)
# #it wont append

In [ ]:
x=[1,'a',2,'b']
type(x)

list

In [ ]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [ ]:
#loop through items in a list

for item in x:
  print(item)

1
a
2
b
3.3


In [ ]:
#lenght of the list
len(x)

5

# list is mutable while tuple is not

In [ ]:
i=0
while(i!=len(x)):
  print(x[i])
  i=i+1

1
a
2
b
3.3


In [ ]:
#Concatenating the 2 list
[1,2]+[3,4]

[1, 2, 3, 4]

In [ ]:
(1,2)+(3,4)

(1, 2, 3, 4)

In [ ]:
#repeat the elements
[10,1,3.3]*3

[10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3]

In [ ]:
#check if the number is present in the list or not
3 in [1,2,3,4,5]

True

In [ ]:
x='This is a string'

In [ ]:
print(x[0])
#first character

T


In [ ]:
print(x[0:1])
#first character method 2

T


In [ ]:
#this will start from 0 and stops before 6 , it also includes the blank space
print(x[0:6])

This i


In [ ]:
#returns the slice starting from the 4th element from the end and stopping before 2
print(x[-4:-2])

ri


In [ ]:
x[-8:-3]

'a str'

In [ ]:
#starts from 0 to before 3
x[:3]

'Thi'

In [ ]:
x[3:]

's is a string'

# above are the character slicing, word slicing will come later

In [ ]:
firstname='MSIS'
lastname='Manipal'

In [ ]:
print(firstname+' '+lastname)

MSIS Manipal


In [ ]:
print(firstname*3)

MSISMSISMSIS


In [ ]:
print('is' in firstname)

False


In [ ]:
firstname='Tom Mitchell Machine learning Scientist'.split(' ')[0]
middlename='Tom Mitchell Machine learning Scientist'.split(' ')[1]
lastname='Tom Mitchell Machine learning Scientist'.split(' ')[-1]

In [ ]:
print(firstname)

Tom


In [ ]:
print(middlename)

Mitchell


In [ ]:
print(lastname)

Scientist


In [ ]:
print(firstname+' '+middlename+' '+lastname)

Tom Mitchell Scientist


In [ ]:
'Chris'+'2'

'Chris2'

In [ ]:
'Chris'+str(2)

'Chris2'

In [ ]:
'Chris'+"2"

'Chris2'

In [ ]:
x={'Tom':'tom.m@gmail.com','Bill Gates':'bill.gates@gmail.com'}

In [ ]:
x['Bill Gates']

'bill.gates@gmail.com'

In [ ]:
x['Adithya']='aditykr142@gmail.com'

In [ ]:
x

{'Tom': 'tom.m@gmail.com',
 'Bill Gates': 'bill.gates@gmail.com',
 'Adithya': 'aditykr142@gmail.com'}

In [ ]:
for name in x:
  print(name)

Tom
Bill Gates
Adithya


In [ ]:
for name in x:
  print(x[name])

tom.m@gmail.com
bill.gates@gmail.com
aditykr142@gmail.com


In [ ]:
x=('Tom','Mitchel','tom.m@gmu.org')
fname,lname,email = x
lname

'Mitchel'

In [ ]:
fname

'Tom'

In [ ]:
x=('Tom','Mitchel','tom.m@gmu.org','MSIS')
fname,lname,email,dept = x
dept

'MSIS'

In [ ]:
sales_record={
    'price':3.24,
    'num_items':4,
    'person':'Tom',
    'email':'tom.m@gm.org'
}


In [ ]:
sent='{} bought {} item(s) at a price of INR {} each for a total of INR{}'

In [ ]:
print(sent.format(sales_record['person'],
      sales_record['num_items'],
      sales_record['price'],
      sales_record['num_items']*sales_record['price']))

Tom bought 4 item(s) at a price of INR 3.24 EACH FOR A TOTAL OF INR12.96


In [ ]:
import datetime as dt
import time as tm

In [ ]:
tm.time()

1755596219.7935903

In [ ]:
from datetime import date
from datetime import time
from datetime import datetime

In [ ]:
today = date.today()
print('today date is',today)

today date is 2025-08-19


In [ ]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2025, 8, 19, 9, 39, 22, 559890)

In [ ]:
delta = dt.timedelta(days=100)

In [ ]:
today=dt.date.today()

In [ ]:
today - delta

datetime.date(2025, 5, 11)

In [ ]:
today>today-delta

True

# **Assignment problems (Lab Day 2) Date-19/08/2025**

1. Implementation of the classic quicksort algorithm in Python.

2. write the output of the following code:

(a)
hello = 'hello'    
world = "world"    
print(hello)       
print(len(hello))  
hw = hello + ' ' + world  
print(hw)  
hw12 = '%s %s %d' % (hello, world, 12)  
print(hw12)

(b)
s = "hello"
print(s.capitalize())  
print(s.upper())       
print(s.rjust(7))      
print(s.center(7))     
print(s.replace('l', '(ell)'))
print('  world '.strip())


3. rewrite the following code using list comprehension technique.

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]


4. Consider the following dictionary

d = {'person': 2, 'cat': 4, 'spider': 8}

write a code to iterate over the keys to print "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"


5. use the items method to rewrite the above code to access the keys and their corresponding values.

6. Write the output of the following lines

	nums = list(range(5))     
	print(nums)               
	print(nums[2:4])          
	print(nums[2:])           
	print(nums[:2])           
	print(nums[:])            
	print(nums[:-1])          
	nums[2:4] = [8, 9]        
	print(nums)               

7. Write the differences between the following two code block

	animals = ['cat', 'dog', 'monkey']

	for animal in animals:

    print(animal)


animals = ['cat', 'dog', 'monkey']

for idx, animal in enumerate(animals):

print('#%d: %s' % (idx + 1, animal))


8. Consider the following code

	nums = [0, 1, 2, 3, 4]

	squares = []

	for x in nums:

    squares.append(x ** 2)

	print(squares)

    rewrite the above code using a list comprehension technique

9. Rewrite the above code to print the square of the even numbers given in the list.

	nums = [0, 1, 2, 3, 4]

10. Write a program using dictionaries to prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

11. Rewrite the above program (10) using the items method to access to keys and their corresponding values.

12 Write the output of the following code
	import numpy as np
	a = np.array([1, 2, 3])   
	print(type(a))            
	print(a.shape)            
	print(a[0], a[1], a[2])   
	a[0] = 5                  
	print(a)                  

b = np.array([[1,2,3],[4,5,6]])    
	print(b.shape)                     
	print(b[0, 0], b[0, 1], b[1, 0])



13. Write the output of the following code

	import numpy as np

	a = np.zeros((2,2))   
	print(a)              

 	b = np.ones((1,2))    
	print(b)              

	c = np.full((2,2), 7)  
	print(c)               

 d = np.eye(2)         
	print(d)              

e = np.random.random((2,2))  
print(e)

14. Create the following rank 2 array with shape (3, 4)
	 [[ 1  2  3  4]
	  [ 5  6  7  8]
	  [ 9 10 11 12]]

	 Use slicing to pull out the subarray consisting of the first 2 rows
	 and columns 1 and 2; b is the following array of shape (2, 2):
	 [[2 3]
	  [6 7]]
15. Consider the following

	a1 = np.array([[1,2], [3, 4], [5, 6]])

    Find the elements of a1 that are bigger than 2;  
    Write your comments on the type and shape of the resultant array.

16. Write your comments on the output of the following code

	import numpy as np

	x = np.array([[1,2],[3,4]])
	y = np.array([[5,6],[7,8]])

	v = np.array([9,10])
	w = np.array([11, 12])

	print(v.dot(w))
	print(np.dot(v, w))

	print(x.dot(v))
	print(np.dot(x, v))

	print(x.dot(y))
	print(np.dot(x, y))

17. Let x = np.array([[1,2],[3,4]])

    Write the code to perform the following

	(a) Compute sum of all elements of x.

	(b) Compute sum of each column of x.

	(c) Compute sum of each row of x.

1. Implementation of the classic quicksort algorithm in Python.


In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

arr = [3, 6, 8, 10, 1, 2, 1]
print(quicksort(arr))


[1, 1, 2, 3, 6, 8, 10]


2. write the output of the following code:

(a)
hello = 'hello'    
world = "world"    
print(hello)       
print(len(hello))  
hw = hello + ' ' + world  
print(hw)  
hw12 = '%s %s %d' % (hello, world, 12)  
print(hw12)

(b)
s = "hello"
print(s.capitalize())  
print(s.upper())       
print(s.rjust(7))      
print(s.center(7))     
print(s.replace('l', '(ell)'))
print('  world '.strip())  

In [ ]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)


hello
5
hello world
hello world 12


In [ ]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))
print('  world '.strip())


Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


3. rewrite the following code using list comprehension technique.

nums = [0, 1, 2, 3, 4]

squares = []

for x in nums:

squares.append(x ** 2)

print(squares)   # Prints [0, 1, 4, 9, 16]

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)  # Prints [0, 1, 4, 9, 16]


[0, 1, 4, 9, 16]


4. Consider the following dictionary

d = {'person': 2, 'cat': 4, 'spider': 8}

write a code to iterate over the keys to print "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for key in d:
    print(f"A {key} has {d[key]} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


5. use the items method to rewrite the above code to access the keys and their corresponding values.

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for key, value in d.items():
    print(f"A {key} has {value} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


6. Write the output of the following lines

	nums = list(range(5))     
	print(nums)               
	print(nums[2:4])          
	print(nums[2:])           
	print(nums[:2])           
	print(nums[:])            
	print(nums[:-1])          
	nums[2:4] = [8, 9]        
	print(nums)          

In [ ]:
nums = list(range(5))
print(nums)               # [0, 1, 2, 3, 4]
print(nums[2:4])          # [2, 3]
print(nums[2:])           # [2, 3, 4]
print(nums[:2])           # [0, 1]
print(nums[:])            # [0, 1, 2, 3, 4]
print(nums[:-1])          # [0, 1, 2, 3]
nums[2:4] = [8, 9]
print(nums)               # [0, 1, 8, 9, 4]


[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


7. Write the differences between the following two code block

	animals = ['cat', 'dog', 'monkey']
	for animal in animals:
    print(animal)


animals = ['cat', 'dog', 'monkey']

for idx, animal in enumerate(animals):

print('#%d: %s' % (idx + 1, animal))


First Code Block:

Iterates over the list animals and prints each animal name directly.

Output is just the animal names.

cat

dog

monkey

Second Code Block:

Uses enumerate() to get both the index and the value, printing the index and animal in a formatted way.

Output includes the index of each animal.

1: cat

2: dog

3: monkey

8. Consider the following code

	nums = [0, 1, 2, 3, 4]

	squares = []

	for x in nums:

  squares.append(x ** 2)



print(squares)


  rewrite the above code using a list comprehension technique


In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)


[0, 1, 4, 9, 16]


9. Rewrite the above code to print the square of the even numbers given in the list.

	nums = [0, 1, 2, 3, 4]

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)


[0, 4, 16]


10. Write a program using dictionaries to prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for key in d:
    print(f"A {key} has {d[key]} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


11. Rewrite the above program (10) using the items method to access to keys and their corresponding values.

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for key, value in d.items():
    print(f"A {key} has {value} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


12 Write the output of the following code

import numpy as np

a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  

b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


13. Write the output of the following code

	import numpy as np

	a = np.zeros((2,2))   
	print(a)              

	b = np.ones((1,2))    
	print(b)              

	c = np.full((2,2), 7)  
	print(c)               

	d = np.eye(2)         
	print(d)              

	e = np.random.random((2,2))  
	print(e)

In [ ]:
import numpy as np

a = np.zeros((2, 2))
print(a)  # [[0. 0.]
          #  [0. 0.]]

b = np.ones((1, 2))
print(b)  # [[1. 1.]]

c = np.full((2, 2), 7)
print(c)  # [[7 7]
          #  [7 7]]

d = np.eye(2)
print(d)  # [[1. 0.]
          #  [0. 1.]]

e = np.random.random((2, 2))
print(e)  # Example output: [[0.234 0.876]
          #                  [0.453 0.123]]


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.51268416 0.29405579]
 [0.82671268 0.44556514]]


14. Create the following rank 2 array with shape (3, 4)

	 [[ 1  2  3  4]

	  [ 5  6  7  8]

	  [ 9 10 11 12]]


Use slicing to pull out the subarray consisting of the first 2 rows

and columns 1 and 2; b is the following array of shape (2, 2):

 [[2 3]

[6 7]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

b = arr[:2, 1:3]
print(b)


[[2 3]
 [6 7]]


15. Consider the following

	a1 = np.array([[1,2], [3, 4], [5, 6]])

    Find the elements of a1 that are bigger than 2;  
    Write your comments on the type and shape of the resultant array.

In [ ]:
a1 = np.array([[1,2], [3, 4], [5, 6]])
result = a1[a1 > 2]
print(result)  # [3 4 5 6]


[3 4 5 6]


16. Write your comments on the output of the following code

	import numpy as np

	x = np.array([[1,2],[3,4]])

	y = np.array([[5,6],[7,8]])

	v = np.array([9,10])

	w = np.array([11, 12])

	print(v.dot(w))

	print(np.dot(v, w))

	print(x.dot(v))

	print(np.dot(x, v))

	print(x.dot(y))
  
	print(np.dot(x, y))

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))  # 9*11 + 10*12 = 99
print(np.dot(v, w))  # Same as above

print(x.dot(v))  # Dot product of matrix x with vector v
print(np.dot(x, v))  # Same as above

print(x.dot(y))  # Matrix multiplication of x and y
print(np.dot(x, y))  # Same as above


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


17. Let x = np.array([[1,2],[3,4]])

    Write the code to perform the following

	(a) Compute sum of all elements of x.

	(b) Compute sum of each column of x.
  
	(c) Compute sum of each row of x.

In [ ]:
x = np.array([[1,2],[3,4]])

# (a) Sum of all elements
print(x.sum())  # 10

# (b) Sum of each column
print(x.sum(axis=0))  # [4 6]

# (c) Sum of each row
print(x.sum(axis=1))  # [3 7]


10
[4 6]
[3 7]
